/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GoogleReviewLinkRouteImport } from './routes/google-review-link'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LebanonRouteImport } from './routes/lebanon'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerStepsRouteImport } from './routes/manager-steps'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as ActivateCodeRouteImport } from './routes/activate.$code'
import { Route as ForIndexRouteImport } from './routes/for.index'
import { Route as ForSlugRouteImport } from './routes/for.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppCardsRouteImport } from './routes/_authenticated/app/cards'
import { Route as AuthenticatedAppHoursRouteImport } from './routes/_authenticated/app/hours'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app/inbox'
import { Route as AuthenticatedAppKnowledgeRouteImport } from './routes/_authenticated/app/knowledge'
import { Route as AuthenticatedAppPhotosRouteImport } from './routes/_authenticated/app/photos'
import { Route as AuthenticatedAppPlanRouteImport } from './routes/_authenticated/app/plan'
import { Route as AuthenticatedAppPostsRouteImport } from './routes/_authenticated/app/posts'
import { Route as AuthenticatedAppReportRouteImport } from './routes/_authenticated/app/report'
import { Route as AuthenticatedAppReviewsRouteImport } from './routes/_authenticated/app/reviews'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppShieldRouteImport } from './routes/_authenticated/app/shield'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleReviewLinkRoute = GoogleReviewLinkRouteImport.update({
  id: '/google-review-link',
  path: '/google-review-link',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LebanonRoute = LebanonRouteImport.update({
  id: '/lebanon',
  path: '/lebanon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerStepsRoute = ManagerStepsRouteImport.update({
  id: '/manager-steps',
  path: '/manager-steps',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateCodeRoute = ActivateCodeRouteImport.update({
  id: '/activate/$code',
  path: '/activate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ForIndexRoute = ForIndexRouteImport.update({
  id: '/for/',
  path: '/for/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSlugRoute = ForSlugRouteImport.update({
  id: '/for/$slug',
  path: '/for/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCardsRoute = AuthenticatedAppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppHoursRoute = AuthenticatedAppHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppKnowledgeRoute =
  AuthenticatedAppKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPhotosRoute = AuthenticatedAppPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPlanRoute = AuthenticatedAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPostsRoute = AuthenticatedAppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReportRoute = AuthenticatedAppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReviewsRoute = AuthenticatedAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppShieldRoute = AuthenticatedAppShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/google-review-link': typeof GoogleReviewLinkRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lebanon': typeof LebanonRoute
  '/login': typeof LoginRoute
  '/manager-steps': typeof ManagerStepsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/design': typeof AuthenticatedDesignRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/start': typeof AuthenticatedStartRoute
  '/a/$token': typeof ATokenRoute
  '/activate/$code': typeof ActivateCodeRoute
  '/for/$slug': typeof ForSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/for/': typeof ForIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/app/cards': typeof AuthenticatedAppCardsRoute
  '/app/hours': typeof AuthenticatedAppHoursRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/app/photos': typeof AuthenticatedAppPhotosRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/posts': typeof AuthenticatedAppPostsRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/shield': typeof AuthenticatedAppShieldRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/google-review-link': typeof GoogleReviewLinkRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lebanon': typeof LebanonRoute
  '/login': typeof LoginRoute
  '/manager-steps': typeof ManagerStepsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/design': typeof AuthenticatedDesignRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/start': typeof AuthenticatedStartRoute
  '/a/$token': typeof ATokenRoute
  '/activate/$code': typeof ActivateCodeRoute
  '/for/$slug': typeof ForSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/for': typeof ForIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/app/cards': typeof AuthenticatedAppCardsRoute
  '/app/hours': typeof AuthenticatedAppHoursRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/app/photos': typeof AuthenticatedAppPhotosRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/posts': typeof AuthenticatedAppPostsRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/shield': typeof AuthenticatedAppShieldRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/google-review-link': typeof GoogleReviewLinkRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lebanon': typeof LebanonRoute
  '/login': typeof LoginRoute
  '/manager-steps': typeof ManagerStepsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/a/$token': typeof ATokenRoute
  '/activate/$code': typeof ActivateCodeRoute
  '/for/$slug': typeof ForSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/for/': typeof ForIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/_authenticated/app/cards': typeof AuthenticatedAppCardsRoute
  '/_authenticated/app/hours': typeof AuthenticatedAppHoursRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/_authenticated/app/photos': typeof AuthenticatedAppPhotosRoute
  '/_authenticated/app/plan': typeof AuthenticatedAppPlanRoute
  '/_authenticated/app/posts': typeof AuthenticatedAppPostsRoute
  '/_authenticated/app/report': typeof AuthenticatedAppReportRoute
  '/_authenticated/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/shield': typeof AuthenticatedAppShieldRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/google-review-link'
    | '/how-it-works'
    | '/lebanon'
    | '/login'
    | '/manager-steps'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/app'
    | '/design'
    | '/partner'
    | '/staff'
    | '/start'
    | '/a/$token'
    | '/activate/$code'
    | '/for/$slug'
    | '/guides/$slug'
    | '/for/'
    | '/guides/'
    | '/app/cards'
    | '/app/hours'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/photos'
    | '/app/plan'
    | '/app/posts'
    | '/app/report'
    | '/app/reviews'
    | '/app/settings'
    | '/app/shield'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/google-review-link'
    | '/how-it-works'
    | '/lebanon'
    | '/login'
    | '/manager-steps'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/design'
    | '/partner'
    | '/staff'
    | '/start'
    | '/a/$token'
    | '/activate/$code'
    | '/for/$slug'
    | '/guides/$slug'
    | '/for'
    | '/guides'
    | '/app/cards'
    | '/app/hours'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/photos'
    | '/app/plan'
    | '/app/posts'
    | '/app/report'
    | '/app/reviews'
    | '/app/settings'
    | '/app/shield'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/faq'
    | '/google-review-link'
    | '/how-it-works'
    | '/lebanon'
    | '/login'
    | '/manager-steps'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/design'
    | '/_authenticated/partner'
    | '/_authenticated/staff'
    | '/_authenticated/start'
    | '/a/$token'
    | '/activate/$code'
    | '/for/$slug'
    | '/guides/$slug'
    | '/for/'
    | '/guides/'
    | '/_authenticated/app/cards'
    | '/_authenticated/app/hours'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/knowledge'
    | '/_authenticated/app/photos'
    | '/_authenticated/app/plan'
    | '/_authenticated/app/posts'
    | '/_authenticated/app/report'
    | '/_authenticated/app/reviews'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/shield'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  GoogleReviewLinkRoute: typeof GoogleReviewLinkRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LebanonRoute: typeof LebanonRoute
  LoginRoute: typeof LoginRoute
  ManagerStepsRoute: typeof ManagerStepsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  ATokenRoute: typeof ATokenRoute
  ActivateCodeRoute: typeof ActivateCodeRoute
  ForSlugRoute: typeof ForSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ForIndexRoute: typeof ForIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-review-link': {
      id: '/google-review-link'
      path: '/google-review-link'
      fullPath: '/google-review-link'
      preLoaderRoute: typeof GoogleReviewLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lebanon': {
      id: '/lebanon'
      path: '/lebanon'
      fullPath: '/lebanon'
      preLoaderRoute: typeof LebanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-steps': {
      id: '/manager-steps'
      path: '/manager-steps'
      fullPath: '/manager-steps'
      preLoaderRoute: typeof ManagerStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/$code': {
      id: '/activate/$code'
      path: '/activate/$code'
      fullPath: '/activate/$code'
      preLoaderRoute: typeof ActivateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/': {
      id: '/for/'
      path: '/for'
      fullPath: '/for/'
      preLoaderRoute: typeof ForIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/$slug': {
      id: '/for/$slug'
      path: '/for/$slug'
      fullPath: '/for/$slug'
      preLoaderRoute: typeof ForSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/cards': {
      id: '/_authenticated/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AuthenticatedAppCardsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/hours': {
      id: '/_authenticated/app/hours'
      path: '/hours'
      fullPath: '/app/hours'
      preLoaderRoute: typeof AuthenticatedAppHoursRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/knowledge': {
      id: '/_authenticated/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AuthenticatedAppKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/photos': {
      id: '/_authenticated/app/photos'
      path: '/photos'
      fullPath: '/app/photos'
      preLoaderRoute: typeof AuthenticatedAppPhotosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/plan': {
      id: '/_authenticated/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AuthenticatedAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/posts': {
      id: '/_authenticated/app/posts'
      path: '/posts'
      fullPath: '/app/posts'
      preLoaderRoute: typeof AuthenticatedAppPostsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/report': {
      id: '/_authenticated/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AuthenticatedAppReportRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reviews': {
      id: '/_authenticated/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AuthenticatedAppReviewsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/shield': {
      id: '/_authenticated/app/shield'
      path: '/shield'
      fullPath: '/app/shield'
      preLoaderRoute: typeof AuthenticatedAppShieldRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppCardsRoute: typeof AuthenticatedAppCardsRoute
  AuthenticatedAppHoursRoute: typeof AuthenticatedAppHoursRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppKnowledgeRoute: typeof AuthenticatedAppKnowledgeRoute
  AuthenticatedAppPhotosRoute: typeof AuthenticatedAppPhotosRoute
  AuthenticatedAppPlanRoute: typeof AuthenticatedAppPlanRoute
  AuthenticatedAppPostsRoute: typeof AuthenticatedAppPostsRoute
  AuthenticatedAppReportRoute: typeof AuthenticatedAppReportRoute
  AuthenticatedAppReviewsRoute: typeof AuthenticatedAppReviewsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppShieldRoute: typeof AuthenticatedAppShieldRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppCardsRoute: AuthenticatedAppCardsRoute,
  AuthenticatedAppHoursRoute: AuthenticatedAppHoursRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppKnowledgeRoute: AuthenticatedAppKnowledgeRoute,
  AuthenticatedAppPhotosRoute: AuthenticatedAppPhotosRoute,
  AuthenticatedAppPlanRoute: AuthenticatedAppPlanRoute,
  AuthenticatedAppPostsRoute: AuthenticatedAppPostsRoute,
  AuthenticatedAppReportRoute: AuthenticatedAppReportRoute,
  AuthenticatedAppReviewsRoute: AuthenticatedAppReviewsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppShieldRoute: AuthenticatedAppShieldRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  GoogleReviewLinkRoute: GoogleReviewLinkRoute,
  HowItWorksRoute: HowItWorksRoute,
  LebanonRoute: LebanonRoute,
  LoginRoute: LoginRoute,
  ManagerStepsRoute: ManagerStepsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  ATokenRoute: ATokenRoute,
  ActivateCodeRoute: ActivateCodeRoute,
  ForSlugRoute: ForSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ForIndexRoute: ForIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
